metrics:
  wal_directory: /tmp/grafana-agent-wal
  global:
    scrape_interval: 15s
  configs:
    - name: default
      scrape_configs:
        - job_name: 'node_exporter'
          static_configs:
            - targets: ['node_exporter:9100']
        - job_name: 'cadvisor'
          static_configs:
            - targets: ['cadvisor:8080']
        - job_name: 'prometheus'
          static_configs:
            - targets: ['prometheus:9090']
